apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-radiosnet
  namespace: pandora
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-radiosnet
  template:
    metadata:
      labels:
        app: api-radiosnet
    spec:
      containers:
      - name: api-radiosnet
        image: stguten/api-radiosnet
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
